<?php

/**
 * DO NOT EDIT THIS FILE, INSTEAD FOLLOW THE STEPS IN config-sample.php:
 *
 * How to configure:
 * 1. Copy this file to config.php
 * 2. In config.php, review steps by each TODO note.
 */

// Error Options
ini_set('display_errors', 0);
ini_set('html_errors', 1);
error_reporting(E_NONE);

// Default config
class Config {
    static $acceptable_mime_patterns = [
        'audio/.*', // Any audio
        'image/.*', // Any image
        'text/.*', // Any text
        'video/.*', // Any video
    ];
    static $auth_token = '';
    static $base_digits = '';
    static $cloudflare_api_key = '';
    static $logging = 0;
    static $logins = [];
    static $redirect_code = 302;
    static $timezone = 'US/Eastern';
    static $url = '';
};
